version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      patch-and-minor:
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      major-updates:
        update-types:
          - "major"
    reviewers:
      - DeWildeDaan